<?php

/**
 * PluginsfGuardUserAttempt
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsfGuardUserAttempt extends BasesfGuardUserAttempt
{
  public function setIp($ip)
  {
    $this->_set('ip', sprintf('%u', ip2long($ip))); // sprintf is to prevent negative ints - http://stackoverflow.com/questions/3062843/php-ip2long-returning-negative-val
  }

  public function getIp()
  {
    return long2ip($this->_get('ip'));
  }
}