<?php

/**
 * PluginsfGuardUserAttemptTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardUserAttemptTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginsfGuardUserAttemptTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginsfGuardUserAttempt');
  }

  public function getActiveAttempts($user_id)
  {
    $q = $this->createQuery('a')
                ->where('user_id = ? AND deleted_at IS NULL', $user_id);

    return $q->execute();
  }
}