## PWC security standards ---------

sfGuardUserPassword:
  actAs: 
    Timestampable: 
      updated:
        disabled: true
  columns:
    user_id:                  { type: integer, notnull: true }
    algorithm:                { type: string(128), default: sha1, notnull: true }
    salt:                     { type: string(128), notnull: true }
    password:                 { type: string(128), notnull: true }
  relations:
    User:
      class:                  sfGuardUser
      local:                  user_id
      foreign:                id
      foreignAlias:           PasswordHistory
      type:                   one
  options:
    symfony:
      filter: false
      form: false

   
sfGuardUserAttempt:
  actAs: 
    Timestampable: 
      updated:
        disabled: true
    SoftDelete:    ~
  columns:
    user_id:                  { type: integer, notnull: true }
    ip:                       { type: integer, unsigned: true, notnull: true }
  relations:
    User:
      class:                  sfGuardUser
      local:                  user_id
      foreign:                id
      foreignAlias:           LoginAttempts
      type:                   one
  options:
    symfony:
      filter: false
      form: false
